---
title: Enhance and Advance
author: McCourt School of Public Policy, Georgetown University
date: Summer 2020
output: 
  html_document:
    theme: flatly
---

<br>

<hr>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Instructor**: [Eric Dunford](http://ericdunford.com/) 

  - Associate Director, MS in Data Science for Public Policy ; Assistant Teaching Professor
  - Email: ed769@georgetown.edu
  - Webinar Materials: http://ericdunford.com/enhance_and_advance_R/

<br>

<hr>

<br>

# Introduction to Python

_Originally offered end-July 2020._

## [Introduction to Data Management in Python](lectures/python_data_manip/data_manip_in_python.html)

### Colab Notebooks

  + [Part 1 - Data in Python using `pandas`](https://drive.google.com/file/d/1FWERVebshSI-RKHZZ-J8gNbsKODNpv6A/view?usp=sharing)
  
  + [Part 2 - Manipulating data in Python using `pandas`](https://drive.google.com/file/d/1TY9KpIoigY8lAYdJclHqPIxA0fH8fnEf/view?usp=sharing)

<br>

<hr>

<br>

# Introduction to `R` 

_The following are materials for the second week of "Introduction to `R`" instruction. Webminar offered mid-June 2020._

<br>


## [Data Wrangling with the `Tidyverse`](lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html)

### _Table of contents for slides_
  - [What is data wrangling?](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#4)
  - [Tidy data](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#7)
  - [Manipulating data with `dplyr`](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#15)
  - [Piping data](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#57)
  - [Joining data](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#64)
  - [Reshaping data using `tidyr`](http://ericdunford.com/enhance_and_advance_R/lectures/wrangling/data_wrangling_enhance_and_advance_intro_to_R.html#82)



### _Application_ 

- [Wrangling Conflict Event Data](lectures/wrangling/walkthroughs/manipulating-conflict-data.nb.html)
  - [Download](lectures/wrangling/walkthroughs/manipulating-conflict-data.Rmd.zip) notebook.


<br>


## [Data Visualization with the `Tidyverse`](lectures/visualization/data_visualization_enhance_and_advance_intro_to_R.html)

### _Table of contents for slides_

  - [The _basic_ components of Data Visualization](http://ericdunford.com/enhance_and_advance_R/lectures/visualization/data_visualization_enhance_and_advance_intro_to_R.html#3)
  - [Grammar of Graphics](http://ericdunford.com/enhance_and_advance_R/lectures/visualization/data_visualization_enhance_and_advance_intro_to_R.html#12)

### _Application_

- Let's walk through the following practice together to explore the relationship between [economic development and life expectancy](lectures/visualization/walkthroughs/gapminder_visualization_practice.Rmd.zip) using the gapminder dataset. I've provided an [answer key](lectures/visualization/walkthroughs/gapminder_visualization_practice_ANSWERS.nb.html) for future reference. 

<br>

<hr>

<br>

